spring.application.name=api_gateway
server.port=8080

# ms-usuarios — nombre del contenedor en Docker es microservicio-usuarios, puerto interno 8080
spring.cloud.gateway.mvc.routes[0].id=ms-auth
spring.cloud.gateway.mvc.routes[0].uri=http://microservicio-usuarios:8080
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.mvc.routes[1].id=ms-usuarios
spring.cloud.gateway.mvc.routes[1].uri=http://microservicio-usuarios:8080
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/usuarios/**

spring.cloud.gateway.mvc.routes[2].id=ms-pacientes
spring.cloud.gateway.mvc.routes[2].uri=http://microservicio-usuarios:8080
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/pacientes/**

spring.cloud.gateway.mvc.routes[3].id=ms-medicos
spring.cloud.gateway.mvc.routes[3].uri=http://microservicio-usuarios:8080
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/api/medicos/**

spring.cloud.gateway.mvc.routes[4].id=ms-personas
spring.cloud.gateway.mvc.routes[4].uri=http://microservicio-usuarios:8080
spring.cloud.gateway.mvc.routes[4].predicates[0]=Path=/api/personas/**

# ms-agendamiento — nombre del contenedor es microservicio-agendamiento, puerto interno 8080
spring.cloud.gateway.mvc.routes[5].id=ms-citas
spring.cloud.gateway.mvc.routes[5].uri=http://microservicio-agendamiento:8080
spring.cloud.gateway.mvc.routes[5].predicates[0]=Path=/api/citas/**

# ms-configuracion — nombre del contenedor es microservicio-configuracion, puerto interno 8080
spring.cloud.gateway.mvc.routes[6].id=ms-jornadas
spring.cloud.gateway.mvc.routes[6].uri=http://microservicio-configuracion:8080
spring.cloud.gateway.mvc.routes[6].predicates[0]=Path=/api/jornadas/**

spring.cloud.gateway.mvc.routes[7].id=ms-especialidades
spring.cloud.gateway.mvc.routes[7].uri=http://microservicio-configuracion:8080
spring.cloud.gateway.mvc.routes[7].predicates[0]=Path=/api/especialidades/**

spring.cloud.gateway.mvc.routes[8].id=ms-configuracion
spring.cloud.gateway.mvc.routes[8].uri=http://microservicio-configuracion:8080
spring.cloud.gateway.mvc.routes[8].predicates[0]=Path=/api/configuracion/**
