services:
  postgres-db:
    image: postgres:15
    container_name: ContenedorPostgresDePiedraAzul
    environment:
      POSTGRES_USER: PiedraAzulUsuario
      POSTGRES_PASSWORD: PiedraAzulContraseña
      POSTGRES_DB: BaseDeDatosPiedraAzul
    ports:
      - "5432:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d