spring.application.name=microservicio_configuracion
server.port=8083

# Base de datos propia del microservicio
spring.datasource.url=jdbc:postgresql://db-configuracion:5432/db_configuracion
spring.datasource.username=piedrazul
spring.datasource.password=piedrazul123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123

# URL de ms-usuarios para consultar médicos
ms.usuarios.url=http://ms-usuarios:8081
